# Generated by Django 2.0 on 2017-12-27 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='compra',
            name='valor_medio',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
