# Generated by Django 2.0 on 2017-12-28 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_auto_20171227_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='valor_medio',
        ),
        migrations.AddField(
            model_name='produto',
            name='valor_medio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
    ]
